import { Routes } from '@angular/router';
import { SolutionsComponent } from './components/main/solutions/solutions.component';
import { WelcomeComponent } from './components/main/welcome/welcome.component';
import { AboutComponent } from './components/pages/about/about.component';
import { GlobalComponent } from './components/pages/our-solutions/global/global.component';
import { StaffingComponent } from './components/pages/our-solutions/staffing/staffing.component';
import { HRPayrollComponent } from './components/pages/our-solutions/hr-payroll/hr-payroll.component';
import { FinanceComponent } from './components/pages/our-solutions/finance/finance.component';
import { DataSupportComponent } from './components/pages/our-solutions/data-support/data-support.component';
import { BlogComponent } from './components/pages/blog/blog.component';
import { CareersComponent } from './components/pages/careers/careers.component';
import { ClientsComponent } from './components/pages/clients/clients.component';
import { MortgageComponent } from './components/pages/our-solutions/mortgage/mortgage.component';
import { MasterVendorComponent } from './components/pages/our-solutions/master-vendor/master-vendor.component';
import { TrainingComponent } from './components/pages/our-solutions/training/training.component';
import { TechnologiesComponent } from './components/pages/our-solutions/technologies/technologies.component';
import { OurSolutionsComponent } from './components/pages/our-solutions/our-solutions.component';
export const routes: Routes = [
  // { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: '', component: WelcomeComponent },
  { path: 'home', component: WelcomeComponent },
  { path: 'solutions', component: OurSolutionsComponent },
  { path: 'about', component: AboutComponent },
  { path: 'solutions/global', component: GlobalComponent },
  { path: 'solutions/staffing', component: StaffingComponent },
  { path: 'solutions/hr-payroll', component: HRPayrollComponent },
  { path: 'solutions/finance', component: FinanceComponent },
  { path: 'solutions/data-support', component: DataSupportComponent },
  { path: 'blog', component: BlogComponent },
  { path: 'careers', component: CareersComponent },
  { path: 'clients', component: ClientsComponent },
  { path: 'solutions/mortgage', component: MortgageComponent },
  { path: 'solutions/master-vendor', component: MasterVendorComponent },
  { path: 'solutions/training', component: TrainingComponent },
  { path: 'solutions/technologies', component: TechnologiesComponent },
  { path: '**', redirectTo: '/home' },
];
